export { default as LoginPage } from './LoginPage'
export { default as RegisterPage } from './RegisterPage'
export { default as CardDetailsPage } from './CardDetailsPage'
export { default as PostingJobPage } from './PostingJobPage'
export { default as CompaniesPage } from './CompaniesPage'
export { default as EmployeeRegisterPage } from './EmployeeRegisterPage'